require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable
  Exclude:
    - 'bin/rubocop'

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Lint/MissingSuper:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Exclude:
    - 'lib/wkhtmltopdf_runner/utils.rb'

Style/OptionalBooleanParameter:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*_spec.rb'
