name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        ruby: [2.7, '3.0', 3.1, 3.2, 3.3, 3.4]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install libpng
      run: sudo apt-get install libpng-dev

    - name: Test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
